-
  name: This playbook installs Nginx
  hosts: servers
  become: yes
  tasks:
    - name: install Nginx
      apt:
        name: Nginx
        package: nginx
        state: latest
    - name: start nginx
      service: 
          name: nginx
          state: started
          enabled: yes